### ISSUE TITLE
feature_sel_module not found

### ISSUE THREAD

**Issue by sumeetssaurav** [Gijom/TEAP#4]
Hello,

While executing the test codes on DEAP database MATLAB is throwing the following errors.

---feature_sel_module not found. 

While looking through the toolbox I found that there is no such modules included in the toolbox. Please include the feature_sel_module.

--Undefined function or variable 'nbTrials'.

It is not clear how to set the value of nbTrials. Please resolve this issue also.

Looking forward for your quick remarks.

Thanking You

Sumeet

**Comment by Gijom** [comment]
Thanks for your feedback.

The problems should now be fixed. Could you please test and confirm ?

**Comment by sumeetssaurav** [comment]
Thanks a lot for your quick reply. The issues reported by me got resolved.
